config/routes.rb
Rails.application.routes.draw do
  # delete 'products/:id', to: 'products#destroy', as: :delete_product
  # get 'products/new', to: 'products#new', as: :new_product
  # post 'products', to: 'products#create'
  # get 'products/:id/edit', to: 'products#edit', as: :edit_product
  # patch 'products/:id', to: 'products#update'
  # get 'products/index'
  # get 'products/:id', to: 'products#show', as: :product
  # get 'products', to: 'products#index'
  resources :products
  root to: 'products#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  validates :title, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.with_attached_photo
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    if product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy

    redirect_to products_path, notice: 'Product was successfully destroyed.', status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo)
  end

  def product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo | compra cosas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error|  %>
      <%= error %>
    <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>



  <%= form.submit %>
<% end %>

app/views/products/_product.html.erb
  <%= link_to product_path(product.id), class: 'product' do %>
    <%= image_tag product.photo, width: 100 if product.photo.attached? %>
    <h2><%= product.title %></h2>
    <span>  <%= product.price  %> $ </span>
  <% end %>

app/views/products/edit.html.erb
<h1>Editar producto</h1>
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<%= render partial: 'product', collection: @products %>

app/views/products/new.html.erb
<h1>Anadir producto</h1>
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/show.html.erb
<h1>this is a  show</h1>
<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>

<h2 class='title'><%= @product.title %></h2>
<p class='description'><%= @product.description %></p>
<span class='price'><%= @product.price %></span>


<%= link_to 'Edit', edit_product_path(@product.id) %>
<%= link_to 'Delete', product_path(@product.id), data: {
  turbo_method: :delete,
  turbo_confirm: 'Are you sure?'
  } %>

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
  <h1>Vendelo</h1>
<% end %>


<p>Esto es un header </p>
<%= link_to 'Añadir producto', new_product_path %>